# Generated by Django 2.1 on 2020-01-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_auto_20191212_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Etiquetado',
            },
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias2', verbose_name='Etiqueta'),
        ),
    ]
