# Generated by Django 2.1 on 2020-01-10 02:57

from django.db import migrations, models
import django.db.models.deletion
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20200101_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idPhotoTramp',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='FKFT',
        ),
        migrations.AddField(
            model_name='repositorio',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.Proyectos', verbose_name='idProyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='image',
            field=models.FileField(upload_to=proyectos.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='FotoTrampa',
        ),
    ]
