# Generated by Django 2.1 on 2020-01-10 03:05

from django.db import migrations, models
import django.db.models.deletion
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20200109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias2', verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=proyectos.models.user_directory_path),
        ),
    ]
